
DROP TABLE RECIPE_TB;


CREATE TABLE RECIPE_TB (
	RECIPE_NM   VARCHAR(100)  NOT NULL,
	INGREDIENTS VARCHAR(1000) NOT NULL, 
	PROCEDURES  VARCHAR(4000) NULL      
);


ALTER TABLE RECIPE_TB
	ADD
		CONSTRAINT PK_RECIPE_TB 
		PRIMARY KEY (
			RECIPE_NM 
		);